spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Customer-Service  # Database URL
    username: root                                     # Database username
    password: root                                     # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver        # MySQL JDBC driver

  jpa:
    hibernate:
      ddl-auto: update                                 # Schema management strategy
    show-sql: true                                     # Show SQL in console
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8090