server:
  port: 8761

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Corrected typo here
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Fixed placeholder syntax here
